version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mqtt_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: p@ssword
      POSTGRES_DB: mqtt_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
